org: dabolus
app: youareamazi-ng
service: youareamazi-ng
frameworkVersion: '2 || 3'
useDotenv: true
variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  memorySize: 768
  lambdaHashingVersion: 20201221
  timeout: 10
  environment:
    NODE_OPTIONS: --enable-source-maps
    STATIC_ASSETS_BASE_URL: https://youareamazi-ng-static.s3.amazonaws.com

plugins:
  - serverless-esbuild
  - serverless-s3-sync
  - serverless-domain-manager

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    packager: yarn
    exclude:
      - aws-sdk
  s3Sync:
    - bucketName: youareamazi-ng-static
      localDir: static
      acl: public-read
  customDomains:
    - http:
        domainName: '*.youareamazi.ng'
        createRoute53Record: true
        endpointType: 'regional'
        securityPolicy: tls_1_2
        apiType: http
        autoDomain: true

package:
  individually: true
  patterns:
    - 'functions/src/templates/**'

functions:
  ejs-renderer:
    handler: functions/src/ejs-renderer.handler
    memorySize: 1536
    timeout: 20
    environment:
      BUILD_OUTPUT: ${file(./scripts/get-build-outputs.js):ejs-renderer}
    events:
      - httpApi:
          path: /
          method: get
      - httpApi:
          path: /sitemap.xml
          method: get
      - httpApi:
          path: /robots.txt
          method: get

resources:
  Resources:
    # The bucket used to store static files
    StaticAssetsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: youareamazi-ng-static
        AccessControl: PublicRead
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - '*'
              AllowedMethods:
                - GET
                - HEAD
